### ISSUE TITLE
Make fx-crash-sig available in iodide

### ISSUE THREAD

**Issue by staktrace** [mozilla/fx-crash-sig#10]
I'm experimenting doing some crash analysis in iodide using the `telemetry.crash` BigQuery table. I really have no idea what I'm doing, but after reading some of the iodide docs it looks like you're supposed to be able to import stuff from PyPI [like so](https://github.com/iodide-project/pyodide/blob/master/docs/pypi.md#installing-packages-from-pypi):

```
pyimport micropip
micropip.install("fx-crash-sig")
```

and when I try that I get:

```
"Couldn't find a pure Python 3 wheel for 'fx-crash-sig'"
```

Is there some way I can work around this, or is there something that needs to be done in terms of publishing this module to PyPI that will fix the error I'm seeing?

/cc @wlach @willkg

**Comment by willkg** [comment]
Looks like there's only a Python 2 wheel on PyPI.

Plus it looks like fx-crash-sig could use some updating.

**Comment by wlach** [comment]
Investigating...

**Comment by wlach** [comment]
Uploading a pure-python wheel should be easy, but this method will fail when getting the crash stack because requests doesn't work inside pyodide:

https://github.com/mozilla/fx-crash-sig/blob/master/fx_crash_sig/symbolicate.py#L132

Probably easy enough to update, but I might suggest just using a local-copy of Jupyter for now. Symbolicating a large number of crash stacks isn't likely to work well inside a browser-based environment.

**Comment by staktrace** [comment]
> Symbolicating a large number of crash stacks isn't likely to work well inside a browser-based environment.

Yeah that's fair. I had kinda assumed without thinking about it that I could turn a pyodide notebook into a dashboard but didn't clue in that the former runs locally while the latter would need to run in the cloud. I can try doing the Jupyter thing locally but I want to make sure whatever I do does contribute to my desired end result of creating a crash signature dashboard that runs in the cloud.

**Comment by wlach** [comment]
Makes sense! I think if we can get a crash signature <-> crash id table in bigquery it should be easy to create such a dashboard by joining it with `telemetry.crash`. Can you validate that you can still get some useful crash signatures for a sample of a week's worth of crash data using jupyter? Once that's done I can help craft an ETL job (maybe we could actually re-use this repo for that purpose).

**Comment by staktrace** [comment]
I didn't install Jupyter locally but I did some ad-hoc thing where I downloaded some data from the STMO telemetry.crash table and ran it through fx-crash-sig locally. I got results that are mostly useful, here is a sampling:

```
Sig: RustMozCrash
Sig: atidxx64.pdb@0xbf256
Sig: atidxx32.pdb@0x5324a4
Sig: atidxx64.pdb@0xaf75b6
Sig: atidxx64.pdb@0xb1699b
Sig: EMPTY: no crashing thread identified
Sig: RustMozCrash
Sig: webrender::picture::TileCacheInstance::update_prim_dependencies
Sig: mozilla::ipc::FatalError | mozilla::ipc::IProtocol::HandleFatalError | mozilla::ipc::IPDLParamTraits<T>::Read
Sig: RustMozCrash
Sig: OOM | unknown | mozalloc_abort | mozalloc_handle_oom | gkrust_shared::oom_hook::hook | std::alloc::rust_oom | alloc::vec::Vec<T>::push<T>
```

The `RustMozCrash` could be better but in general the results seem reasonable. Note that I couldn't just take the `additional_data` column from `telemetry.crash` unmodified; I had to take the `payload.metadata` as well and stuff it back into the `additional_data` before I could pass it to fx-crash-sig.

Relevant bits of the ad-hoc machinery I set up:

```
SELECT
    additional_properties,
    TO_JSON_STRING(payload.metadata) AS metadata,
    [...]
FROM telemetry.crash
WHERE
    [...]
;
```

```
for r in dataset.query_result.data.rows:
  j = json.loads(r.additional_properties)
  j["payload"]["metadata"] = json.loads(r.metadata)
  try:
    payload = proc.symbolicate(j["payload"])
  except TypeError:
    continue
  if payload is None:
    continue
  try:
    sig = proc.get_signature_from_symbolicated(payload).signature
  except TypeError:
    continue

  print("Sig: %s" % sig)
```

**Comment by wlach** [comment]
Very cool, let me dig into https://bugzilla.mozilla.org/show_bug.cgi?id=1623626 and then we can look into making a derived dataset.

**Comment by willkg** [comment]
I think the need for this has passed, so I'm going to close it out.
