### ISSUE TITLE
transfer to mozilla and adjust admin

### ISSUE THREAD

**Issue by willkg** [mozilla/fx-crash-sig#6]
To make this reliable to use and easier to maintain, we should transfer this into the mozilla org on GitHub. I can help with that.

Further, we should probably add a couple more admin. Will suggested him and me. I think at least him seems like a good idea. I'm fine with just sending in PRs.

**Comment by willkg** [comment]
Also, whoever is an admin should also have privileges to upload releases to PyPI.

**Comment by Ben-Wu** [comment]
Sure I'd be happy to do that.  What do I need to do?

wlach is an owner of the pypi project.

**Comment by willkg** [comment]
@wlach Which GitHub org do you want to switch this to?

**Comment by wlach** [comment]
@willkg sorry, I somehow missed this. Just plain `mozilla` should be fine.

**Comment by wlach** [comment]
Not sure if it helps, but there is some discussion on Mozilla's administration of the github repository here: https://wiki.mozilla.org/Github

Most likely we will need to get in touch with an org admin to facilitate this process.

**Comment by wlach** [comment]
@Ben-Wu Actually could you transfer it to me? I can handle the mechanics of transferring the repository to Mozilla (which will probably involve me hassling a bunch of people on internal channels).

The procedure to transfer a repo is documented here:

https://help.github.com/en/articles/transferring-a-repository

**Comment by willkg** [comment]
If @Ben-Wu makes me an admin, I can switch it over to mozilla.

**Comment by Ben-Wu** [comment]
It doesn't look like I can add an admin unless the repo is part of an organization.  I can transfer ownership though.  Who wants to take it?  @wlach or @willkg ?

**Comment by wlach** [comment]
Probably getting it transferred to one of us is the important thing. May as well just make it @willkg since he most recently offered to take care of the rest. Hopefully it should be smooth sailing after that.

**Comment by willkg** [comment]
GitHub is so funky sometimes.

I have deleted my fork, so you can transfer to me and I'll transfer to mozilla. Whee!

**Comment by willkg** [comment]
I transferred it to mozilla. Then I wrote up a bug to get admin access:

https://bugzilla.mozilla.org/show_bug.cgi?id=1558292

I figure we can add Ben after they give someone permissions.

**Comment by willkg** [comment]
I think we're all set here!
