### ISSUE TITLE
set up CircleCI

### ISSUE THREAD

**Issue by willkg** [mozilla/fx-crash-sig#8]
Whenever someone makes a pull request, we should have CI run through the tests, linting, and anything else we want robots to do to make it easier to review changes.

This issue covers setting that up with CircleCI.

**Comment by carrycooldude** [comment]
I want to work on this....

**Comment by wlach** [comment]
> I want to work on this....

Thanks for your interest! Unfortunately this isn't a great task for a new contributor. If you're interested in other opportunities to contribute to Mozilla software, see: https://codetribute.mozilla.org/

**Comment by willkg** [comment]
I see circleci is set up, so I think we're good here.

https://app.circleci.com/pipelines/github/mozilla/fx-crash-sig
